# Generated by Django 5.1.3 on 2024-11-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repeat', models.CharField(choices=[('none', 'Does not repeat'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='none', max_length=10)),
                ('repeat_every', models.PositiveIntegerField(blank=True, null=True)),
                ('days_of_week', models.CharField(blank=True, max_length=255, null=True)),
                ('day_of_month', models.PositiveIntegerField(blank=True, null=True)),
                ('month_of_year', models.PositiveIntegerField(blank=True, null=True)),
                ('minute', models.PositiveIntegerField(default=0)),
                ('hour', models.PositiveIntegerField(default=9)),
            ],
        ),
    ]
